### ISSUE TITLE
Node 13 support?

### ISSUE THREAD

**Issue by GunnarAK** [mysticatea/eslint-utils#39]
v3.0.0 of this package supports the following node versions:
```
"engines": {
    "node": "^10.0.0 || ^12.0.0 || >= 14.0.0"
  },
```

Why is node 13 ignored/disabled?

**Comment by WikiRik** [comment]
Node 13 was already end-of-life with the release of 3.0.0 so that's probably why (see also https://nodejs.org/en/about/releases/ )
