### ISSUE TITLE
Support ESLint 7.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [mysticatea/eslint-utils#6]
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

It would be awesome to have official ESLint 7 support. 👊
I'm happy to help where I can of course 🙂

**Comment by chrisbobbe** [comment]
Looks like #7 is ready to go, for this, and would unblock lots of other things, including ([reportedly](https://github.com/mysticatea/eslint-utils/pull/7#issuecomment-663628401)) the release of Create React App v4! 🎉
